### ISSUE TITLE
check mathjax is working

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#15] opened 2022-01-20 00:15 UTC
Hopefully this just works, but should check once @fontikar gets to migrating the statistics pages

**Comment by fontikar** [comment] 2022-01-21 06:09
Is this referring to mathematical equations written in LaTex?  e.g in Linear Regression and GLM? If so, they are not. Will definitely need to fix!

**Comment by wcornwell** [comment] 2022-01-21 06:14
hmmm may have to read/understand this https://github.com/rstudio/blogdown/issues/36

**Comment by wcornwell** [comment] 2022-01-24 20:46
@fontikar can you check if the equations are formatting correctly for you?

**Comment by fontikar** [comment] 2022-01-24 22:02
Hi @wcornwell
I had a look at Linear Models and Mixed Models but it looks like its sitll not working! I will take a closer look today too!

![Screen Shot 2022-01-25 at 9 01 39 am](https://user-images.githubusercontent.com/12161802/150872377-ecaf7192-7e61-476c-98cb-26d0dc865062.png)

**Comment by wcornwell** [comment] 2022-01-24 22:08
hmmmm

<img width="748" alt="Screen Shot 2022-01-25 at 9 07 45 am" src="https://user-images.githubusercontent.com/5534161/150873189-b40fbf68-580a-4395-bde6-12b6eda440dc.png">

**Comment by wcornwell** [comment] 2022-01-24 22:12
could be a caching issue?  

I had to re-knit all the rmd files and my `git status` call now has a zillion uncommited changes
<img width="637" alt="Screen Shot 2022-01-25 at 9 10 52 am" src="https://user-images.githubusercontent.com/5534161/150873568-4c9f6e1c-eca8-4fdb-9b5e-a8484dca9306.png">
:

**Comment by fontikar** [comment] 2022-01-24 22:12
![Screen Shot 2022-01-25 at 9 11 42 am](https://user-images.githubusercontent.com/12161802/150873552-2a98c4fa-f1cc-4604-8d2e-028f03b1a3c9.png)
 ITS WORKING!!!!!!!! THANKS WILL! What a lovely simple solution! (I had realised I hadn't fetched your recent changes in layout/partials) - you can most certainly close the issue!

**Comment by fontikar** [comment] 2022-01-24 22:13
> could be a caching issue?
> 
> I had to re-knit all the rmd files and my `git status` call now has a zillion uncommited changes <img alt="Screen Shot 2022-01-25 at 9 10 52 am" width="637" src="https://user-images.githubusercontent.com/5534161/150873568-4c9f6e1c-eca8-4fdb-9b5e-a8484dca9306.png"> :

Interesting....I often see files with .Rmd.lock appearing when I reknit and then disappearing. Did you use the knit button or did you use `blogdown::build_rmd()`?

**Comment by wcornwell** [comment] 2022-01-24 22:14
i was using `blogdown::build_site(build_rmd=TRUE)` but i'm not at all sure what's best practice...

**Comment by fontikar** [comment] 2022-01-24 22:16
I believe `blogdown::build_site(build_rmd=TRUE)` includes the `build_rmd()` function. Anything suspicious in `check_site()` output?

**Closed as completed** 2022-01-24 22:16 UTC

**Comment by wcornwell** [comment] 2022-01-24 22:26
`check_site()` lots of useful tips there!  good one!
